export enum IQuizTypes {
    START_GAME             = '@quiz/START_GAME',
    NEXT_QUESTION          = '@quiz/NEXT_QUESTION',
    END_GAME               = '@quiz/END_GAME',
    LOAD_QUESTIONS_REQUEST = '@quiz/LOAD_QUESTIONS_REQUEST',
    LOAD_QUESTIONS_SUCCESS = '@quiz/LOAD_QUESTIONS_SUCCESS',
    LOAD_QUESTIONS_FAILURE = '@quiz/LOAD_QUESTIONS_FAILURE'
}